---

- name: Copy web files to server
  copy: 
    src: "{{ item }}"
    dest: "/var/www/html/"
  with_items: 
    - system_out.php
  notify: restart httpd
  tags:
    - content

- name: Copy msqyl stuff to server
  template:
    src: mysql.php
    dest: "/var/www/html/mysql.php"
  notify: restart httpd
  tags:
    - content